import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0D0D0D' },
  scrollContent: { padding: 20, paddingBottom: 40 },
  header: { marginBottom: 24 },
  headerTitle: { fontSize: 22, fontWeight: '900', color: '#FFFFFF' },
  headerSubtitle: { fontSize: 13, color: '#AAAAAA', marginTop: 4 },

  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },
  sectionBlock: { marginBottom: 28 },
  addButton: {
    backgroundColor: '#E63030',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  addButtonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  emptyText: { color: '#777777', fontSize: 13, textAlign: 'center', marginTop: 16 },

  // Inadimplentes
  inadimplenteCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
  },
  inadimplenteNome: { color: '#FFFFFF', fontWeight: '600', fontSize: 14 },
  inadimplenteDias: { color: '#777777', fontSize: 12, marginTop: 2 },
  inadimplenteValor: { color: '#FF5555', fontWeight: '700', fontSize: 14 },

  // Gráfico de barras (alunos por plano)
  chartCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    padding: 16,
  },
  chartRow: { marginBottom: 14 },
  chartRowHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  chartLabel: { color: '#CCCCCC', fontSize: 13 },
  chartValue: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  chartTrack: { height: 8, backgroundColor: '#2A2A2A', borderRadius: 4, overflow: 'hidden' },
  chartBar: { height: 8, backgroundColor: '#E63030', borderRadius: 4 },

  // Chamados
  chamadoCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    padding: 14,
    marginBottom: 10,
  },
  chamadoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  chamadoEquipamento: { color: '#FFFFFF', fontWeight: '700', fontSize: 14, flex: 1, marginRight: 8 },
  chamadoDescricao: { color: '#AAAAAA', fontSize: 13, marginTop: 6 },
  chamadoThumb: { width: '100%', height: 140, borderRadius: 8, marginTop: 10, backgroundColor: '#0D0D0D' },
  chamadoFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
  chamadoData: { color: '#666666', fontSize: 11 },

  badge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  badgeText: { fontSize: 11, fontWeight: '700' },
  badgeAlta: { backgroundColor: '#3A1414' },
  badgeAltaText: { color: '#FF5555' },
  badgeCritica: { backgroundColor: '#4A1010' },
  badgeCriticaText: { color: '#FF2C2C' },
  badgeMedia: { backgroundColor: '#3A2E14' },
  badgeMediaText: { color: '#FFB800' },
  badgeBaixa: { backgroundColor: '#14301A' },
  badgeBaixaText: { color: '#4CD964' },

  // Modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: '#141414',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 32,
    maxHeight: '88%',
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: '#FFFFFF', marginBottom: 16 },
  label: { color: '#CCCCCC', fontSize: 13, marginBottom: 6, marginTop: 14 },
  input: {
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    color: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  textArea: { minHeight: 80, textAlignVertical: 'top' },

  // Seleção de equipamento (chips)
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
  chip: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  chipSelected: { borderColor: '#E63030', backgroundColor: '#2A1414' },
  chipText: { color: '#AAAAAA', fontSize: 13, fontWeight: '600' },
  chipTextSelected: { color: '#FFFFFF' },

  prioridadeRow: { flexDirection: 'row', marginTop: 6, flexWrap: 'wrap' },
  prioridadeOption: {
    flex: 1,
    minWidth: '47%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    paddingVertical: 10,
    alignItems: 'center',
    marginRight: 8,
    marginBottom: 8,
  },
  prioridadeOptionSelected: { borderColor: '#E63030', backgroundColor: '#2A1414' },
  prioridadeOptionText: { color: '#AAAAAA', fontSize: 13, fontWeight: '600' },
  prioridadeOptionTextSelected: { color: '#FFFFFF' },

  imagePickerRow: { flexDirection: 'row', marginTop: 6 },
  imagePickerButton: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    borderStyle: 'dashed',
    paddingVertical: 14,
    alignItems: 'center',
    marginRight: 8,
  },
  imagePickerButtonText: { color: '#AAAAAA', fontSize: 13, fontWeight: '600' },
  imagePreviewWrapper: { marginTop: 6 },
  imagePreview: { width: '100%', height: 160, borderRadius: 10, backgroundColor: '#0D0D0D' },
  imageRemoveButton: { marginTop: 8, alignSelf: 'flex-start' },
  imageRemoveButtonText: { color: '#FF5555', fontSize: 13, fontWeight: '600' },

  modalButtons: { flexDirection: 'row', marginTop: 24 },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    marginRight: 10,
  },
  cancelButtonText: { color: '#CCCCCC', fontWeight: '600' },
  submitButton: { flex: 1, paddingVertical: 14, alignItems: 'center', borderRadius: 8, backgroundColor: '#E63030' },
  submitButtonText: { color: '#FFFFFF', fontWeight: '700' },
});